### ISSUE TITLE
Crashes with vector drawables

### ISSUE THREAD

**Issue by coolmyll** [lilei644/SpringActionMenu#1]
Vector drawables cause crashes.

`08-01 17:44:10.141 785-810/system_process W/WindowManager: Failed looking up window
                                                           java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@9c06915 does not exist
                                                               at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9462)
                                                               at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9453)
                                                               at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2395)
                                                               at com.android.server.wm.Session.remove(Session.java:193)
                                                               at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3290)
                                                               at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5923)
                                                               at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3629)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                               at com.android.server.ServiceThread.run(ServiceThread.java:46)`

**Comment by lilei644** [comment]
Thank you for your feedback, bug has been fixed, and now you can use vector drawable.

**Comment by coolmyll** [comment]
Thank you. It works fine now.
